### ISSUE TITLE
当用js来控制隐藏还是显示时就会有问题。

### ISSUE THREAD

**Issue by daaao** [jawil/datePicker#1]
![image](https://cloud.githubusercontent.com/assets/18110266/26255029/fdb7c6fa-3cea-11e7-97ae-e3bab4898fb8.png)

默认隐藏，然后JS控制隐藏显示，就会出现这种情况

**Comment by jawil** [comment]
。。。用babel编译过了吗，用的什么浏览器，还有报什么错误了吗？这个是单独的还是已经放在了某个项目中了？

**Comment by Jialufeng** [comment]
@izhijian  你这个应该是默认隐藏了吧，
window.addEventListener('DOMContentLoaded', function() {
            datePicker({
                appointDays: 300, // 默认可以预约未来7天
                minuteLater: 180, // 默认只能预约20分钟之后,如果两个小时就填120
                interval: 10, // 分钟的间隔，默认一分钟
                startDate: 8, //每天可选择最早时间
                endDate: 20, //每天可选择最晚时间
                callBack: function(timeStr, timeStamp) { //点击确认获取到的时间戳和时间字符串
                    console.log(timeStr, timeStamp)
                    $('.sendTime').html(timeStamp)
                }
            });
            $('.mf-picker').hide();

        }, false)
      加载完后隐藏就可以了。

**Comment by Jialufeng** [comment]
能不能设置默认选择时间为2天后？？

**Comment by jawil** [comment]
@Jialufeng 不行，我明天改一下，再暴露一个接口参数出来

**Comment by Jialufeng** [comment]
@jawil  靠谱，本来想试着改下你源码。搞了一下午，小复杂。公司太忙，放弃了。哈

**Comment by jawil** [comment]
逻辑和交互太多，一时半会看不明白的，虽然都有注释。@Jialufeng

**Comment by Jialufeng** [comment]
你写的挺棒的，逻辑清晰 。  @jawil

**Comment by jawil** [comment]
@Jialufeng  改好了 测一测看有啥问题没，加了两个API参数

**Comment by liujiale01** [comment]
好像不可以连续选两次时间

**Comment by jawil** [comment]
你要选一个范围么，我这做的就是选一次的预约时间，你说一下你的具体需求吧 @liujiale01

**Comment by Jialufeng** [comment]
@jawil  哈，那个默认选择几天后的时间 我没说清楚，抱歉哈。如果默认是明天，今天还符合预约的小时范围内，那还可以选择今天，大概是这样的

**Comment by Jialufeng** [comment]
@jawil  简单的描述就是  默认时间  可以往前选，或者往后选。

**Comment by jawil** [comment]
选择时间不是用户选择的吗，为什么今天可以预约，你还要默认给他设置为明天，我觉得这种需求很鸡肋。
直接默认今天，用户想选择明天可以自己滑动啊 @Jialufeng 其实满足这个需求实现也是小菜一碟，无非就是UI和index默认值改一下，或者暴露再暴露一个接口，不过我觉得产品有点过分了 @Jialufeng

**Comment by Jialufeng** [comment]
恩，产品比较灵活。我们是租车行业 ，用户选择用车 开始时间，和结束时间后，在使用期间可以修改结束时间，（修改结束时间，默认结束时间）可选择 提前结束，或者往后延。 @jawil

**Comment by jawil** [comment]
这个插件当初也是因为预约打车有这个需求才写的，默认设置明天你尝试改一下，我这几天开发一个TOC的谷歌插件，比较忙，逻辑比这个复杂多了，要崩溃了 @Jialufeng  要是晚上之前没弄好，我晚上抽时间改一下吧，你把具体的说清楚就行

**Comment by Jialufeng** [comment]
谷歌插件  👍。   我试了一下，默认设置明天，开始时间就是明天，不能往前选择了。我现在版本是之前写的，不是很灵活，所以想换一个试试，9月1号下午上线，不是很着急，没事。有时间我先自己看看，能改的话，我尽量自己改下。谢谢~ @jawil 🤗

**Comment by Jialufeng** [comment]
@jawil  搞定了，Picker 有2个参数，第二个就是设置默认几天后。👍

**Comment by jawil** [comment]
自己改代码搞定了？不错啊👍，我的chrome插件终于也快搞定了，开发快一个星期了 @Jialufeng

**Comment by Jialufeng** [comment]
@jawil  哈哈   主要你代码写的清晰，不知道我改完后有没有bug 还没有上线。

**Comment by jawil** [comment]
消失人口突然诈尸😂

**Comment by Jialufeng** [comment]
vue 的 mounted 方法里调用datePicker({...})
会报错："TypeError: _datePicker2.default is not a constructor"；
class datePicker  不是一个构造函数，但是我明明引入了。

**Comment by jawil** [comment]
你是import引入进去的吗？用require引入吧，我没有兼容ES6的import导出

**Comment by jawil** [comment]
var datePicker = require('......../dataPicker.js')

**Comment by Jialufeng** [comment]
这样啊，好的，我试一下。

**Comment by Jialufeng** [comment]
@jawil  我看你 module.exports = datePicker  最后导出了。
子组件：var datePicker = require('......../dataPicker.js') ；

  打印 datePicker  是个base64 。。。是我搞错了？

**Comment by jawil** [comment]
.........../dataPicker.js  是指最后打包之后的代码具体放在那里的路径，你就这样复制过去了？

**Comment by Jialufeng** [comment]
哦，要单独打包完在copy过去？哈，我直接改的源文件。

**Comment by Jialufeng** [comment]
@jawil  有点后悔了，不如让你帮我改下，把你代码改了好多，好奔溃啊
哈哈 发现好几个问题  比如 默认多少分钟后（minuteLater）大于今天剩余的分钟数 天数不会加1。。，
哦，看到了，可以把分钟转换为afterDay。

**Comment by jawil** [comment]
...

**Comment by Jialufeng** [comment]
哈，也没什么事，主要这需求，有点蛋疼 。

**Comment by jawil** [comment]
能理解，因为当初这个是我自己写的，所以我对产品说，你尽管提需求，实现不鸟算我输。(:逃

**Comment by Jialufeng** [comment]
👍   🐂 逼。

**Comment by Jialufeng** [comment]
@jawil  我给改懵逼了，擦，改乱了，忘记备份＝／＝
![image](https://user-images.githubusercontent.com/16443142/31324858-9597e774-ac7c-11e7-8777-9e7681cc73f4.png) 加这两个参数麻烦么？

**Comment by jawil** [comment]
你们还没上线？一个预约的功能搞得这么麻烦，本末倒置啊

**Comment by Jialufeng** [comment]
线上有一个，就是体验不好，想做个屌一点的，我在看看吧。

**Comment by Jialufeng** [comment]
@jawil 搞定了^_^。

**Comment by jawil** [comment]
。。。估计你现在对代码熟悉度比我还熟了，2333

**Comment by Jialufeng** [comment]
哈，我感觉把你这个改了一遍，最后还剩3个参数。。。
![image](https://user-images.githubusercontent.com/16443142/31330574-9c8a0d28-aca4-11e7-934b-a4607be81edd.png)
