### ISSUE TITLE
怎么加个选择现在？

### ISSUE THREAD

**Issue by sunny-tong** [jawil/datePicker#4]
能不能在小时的li中添加一个现在的选项？

**Comment by jawil** [comment]
不能，当初有个现在选择，被我们产品给砍掉了，我是模仿滴滴做的

**Comment by jawil** [comment]
没有这个配置项，要改的话你修改一下dom的结构就行

**Comment by sunny-tong** [comment]
我直接添加个现在选出来的时间不行

**Comment by jawil** [comment]
现在，你要解析对应的时间的，要添加js做处理的，你加个现在代码认识"现在"吗，代码只会解析证正则配到的数字然后转成时间戳。。。要想改的话也简单，你把默认预约多少分钟之后改为0，不就是现在吗，你先试一试，我有段时间没看这代码了，不行的话我晚上试一试帮你改

**Comment by sunny-tong** [comment]
预约多少分钟改为0后还是不行

**Comment by jawil** [comment]
叫你们产品出来，我跟他怼😂，我当初加了现在被砍掉了，现在去掉了你们又要加现在。。。就是今天预约加个现在，明天的不用加是吧？

**Comment by sunny-tong** [comment]
是的

**Comment by sunny-tong** [comment]
我们这边啥都没有，我们这边弄后端的，前端插件、页面样式都要自己搞，公司不正规没办法

**Comment by sunny-tong** [comment]
我们现在做的功能就是和滴滴一个样，领导根本就不知道自己想要什么，只能模仿人家的做

**Comment by jawil** [comment]
你咋这么6，一个人搞这么多，能搞得精吗，搞个粗糙的以后有得你维护的。。。

**Comment by sunny-tong** [comment]
搞不精，我就会点jquery，以前做的项目都有ui的，根据静态页面做就行，现在这公司都要自己搞

**Comment by sunny-tong** [comment]
我把你的min.js格式化了，改了个现在，但是移动今天、明天然后回到今天又没了，选择后也不是显示现在。

**Comment by jawil** [comment]
不要改那个，改src里面，然后重新build打包

**Comment by jawil** [comment]
我给你改吧，你这么辛苦，本来不想改的，因为这个需求之前被砍掉了，所以我是不想加的

**Comment by sunny-tong** [comment]
感谢，辛苦你了

**Comment by sunny-tong** [comment]
build 还没用过

**Comment by jawil** [comment]
我看了下，改DOM结构要改不少代码，这样处理一下。

把index.html文件下面的配置minuteLater的20改为0就是现在时间了，你们boss非要把这个结构改成一栏的现在，我也没辙，改动的地方有点大。

![](https://ws1.sinaimg.cn/large/006tNc79gy1fjwqs4im8zj30pa0k7gqd.jpg)

**Comment by sunny-tong** [comment]
我现在是设置的0，但是interval设置10的话就不会是现在的时间了默认是10的倍数

**Comment by jawil** [comment]
interval也设置为0，交互的一些样式细节没必要太在乎，交互体验良好逻辑没有bug能实现功能就ok了，又不影响使用，这些东西看起来很容易，写起来可不容易，可惜你们老板并不知道。。。

**Comment by sunny-tong** [comment]
嗯，感谢

**Comment by jawil** [comment]
nterval也设置为1。。。说错了

**Comment by sunny-tong** [comment]
好的
